/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/student'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as StudentWishlistRouteImport } from './routes/student.wishlist'
import { Route as StudentSubscriptionRouteImport } from './routes/student.subscription'
import { Route as StudentScheduleRouteImport } from './routes/student.schedule'
import { Route as StudentLearnRouteImport } from './routes/student.learn'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentCertificatesRouteImport } from './routes/student.certificates'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as StudentQuizzesIndexRouteImport } from './routes/student.quizzes.index'
import { Route as StudentQuizzesIdRouteImport } from './routes/student.quizzes.$id'
import { Route as StudentQuizResultIdRouteImport } from './routes/student.quiz-result.$id'
import { Route as StudentCoursesIdRouteImport } from './routes/student.courses.$id'
import { Route as StudentCourseIdRouteImport } from './routes/student.course.$id'

const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const StudentWishlistRoute = StudentWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSubscriptionRoute = StudentSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => StudentRoute,
} as any)
const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLearnRoute = StudentLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCertificatesRoute = StudentCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => StudentRoute,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentQuizzesIndexRoute = StudentQuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuizzesIdRoute = StudentQuizzesIdRouteImport.update({
  id: '/quizzes/$id',
  path: '/quizzes/$id',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuizResultIdRoute = StudentQuizResultIdRouteImport.update({
  id: '/quiz-result/$id',
  path: '/quiz-result/$id',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesIdRoute = StudentCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentCoursesRoute,
} as any)
const StudentCourseIdRoute = StudentCourseIdRouteImport.update({
  id: '/course/$id',
  path: '/course/$id',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/courses/$id': typeof CoursesIdRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/learn': typeof StudentLearnRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/student/wishlist': typeof StudentWishlistRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/course/$id': typeof StudentCourseIdRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/quiz-result/$id': typeof StudentQuizResultIdRoute
  '/student/quizzes/$id': typeof StudentQuizzesIdRoute
  '/student/quizzes/': typeof StudentQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/courses/$id': typeof CoursesIdRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/learn': typeof StudentLearnRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/student/wishlist': typeof StudentWishlistRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/student': typeof StudentIndexRoute
  '/student/course/$id': typeof StudentCourseIdRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/quiz-result/$id': typeof StudentQuizResultIdRoute
  '/student/quizzes/$id': typeof StudentQuizzesIdRoute
  '/student/quizzes': typeof StudentQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/courses/$id': typeof CoursesIdRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/learn': typeof StudentLearnRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/student/wishlist': typeof StudentWishlistRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/course/$id': typeof StudentCourseIdRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/quiz-result/$id': typeof StudentQuizResultIdRoute
  '/student/quizzes/$id': typeof StudentQuizzesIdRoute
  '/student/quizzes/': typeof StudentQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/student'
    | '/courses/$id'
    | '/student/certificates'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/learn'
    | '/student/schedule'
    | '/student/subscription'
    | '/student/wishlist'
    | '/admin/'
    | '/courses/'
    | '/student/'
    | '/student/course/$id'
    | '/student/courses/$id'
    | '/student/quiz-result/$id'
    | '/student/quizzes/$id'
    | '/student/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/courses/$id'
    | '/student/certificates'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/learn'
    | '/student/schedule'
    | '/student/subscription'
    | '/student/wishlist'
    | '/admin'
    | '/courses'
    | '/student'
    | '/student/course/$id'
    | '/student/courses/$id'
    | '/student/quiz-result/$id'
    | '/student/quizzes/$id'
    | '/student/quizzes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/signup'
    | '/student'
    | '/courses/$id'
    | '/student/certificates'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/learn'
    | '/student/schedule'
    | '/student/subscription'
    | '/student/wishlist'
    | '/admin/'
    | '/courses/'
    | '/student/'
    | '/student/course/$id'
    | '/student/courses/$id'
    | '/student/quiz-result/$id'
    | '/student/quizzes/$id'
    | '/student/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRouteWithChildren
  CoursesIdRoute: typeof CoursesIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/student/wishlist': {
      id: '/student/wishlist'
      path: '/wishlist'
      fullPath: '/student/wishlist'
      preLoaderRoute: typeof StudentWishlistRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/subscription': {
      id: '/student/subscription'
      path: '/subscription'
      fullPath: '/student/subscription'
      preLoaderRoute: typeof StudentSubscriptionRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/schedule': {
      id: '/student/schedule'
      path: '/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/learn': {
      id: '/student/learn'
      path: '/learn'
      fullPath: '/student/learn'
      preLoaderRoute: typeof StudentLearnRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/certificates': {
      id: '/student/certificates'
      path: '/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof StudentCertificatesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student/quizzes/': {
      id: '/student/quizzes/'
      path: '/quizzes'
      fullPath: '/student/quizzes/'
      preLoaderRoute: typeof StudentQuizzesIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quizzes/$id': {
      id: '/student/quizzes/$id'
      path: '/quizzes/$id'
      fullPath: '/student/quizzes/$id'
      preLoaderRoute: typeof StudentQuizzesIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quiz-result/$id': {
      id: '/student/quiz-result/$id'
      path: '/quiz-result/$id'
      fullPath: '/student/quiz-result/$id'
      preLoaderRoute: typeof StudentQuizResultIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses/$id': {
      id: '/student/courses/$id'
      path: '/$id'
      fullPath: '/student/courses/$id'
      preLoaderRoute: typeof StudentCoursesIdRouteImport
      parentRoute: typeof StudentCoursesRoute
    }
    '/student/course/$id': {
      id: '/student/course/$id'
      path: '/course/$id'
      fullPath: '/student/course/$id'
      preLoaderRoute: typeof StudentCourseIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface StudentCoursesRouteChildren {
  StudentCoursesIdRoute: typeof StudentCoursesIdRoute
}

const StudentCoursesRouteChildren: StudentCoursesRouteChildren = {
  StudentCoursesIdRoute: StudentCoursesIdRoute,
}

const StudentCoursesRouteWithChildren = StudentCoursesRoute._addFileChildren(
  StudentCoursesRouteChildren,
)

interface StudentRouteChildren {
  StudentCertificatesRoute: typeof StudentCertificatesRoute
  StudentCoursesRoute: typeof StudentCoursesRouteWithChildren
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentLearnRoute: typeof StudentLearnRoute
  StudentScheduleRoute: typeof StudentScheduleRoute
  StudentSubscriptionRoute: typeof StudentSubscriptionRoute
  StudentWishlistRoute: typeof StudentWishlistRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentCourseIdRoute: typeof StudentCourseIdRoute
  StudentQuizResultIdRoute: typeof StudentQuizResultIdRoute
  StudentQuizzesIdRoute: typeof StudentQuizzesIdRoute
  StudentQuizzesIndexRoute: typeof StudentQuizzesIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCertificatesRoute: StudentCertificatesRoute,
  StudentCoursesRoute: StudentCoursesRouteWithChildren,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentLearnRoute: StudentLearnRoute,
  StudentScheduleRoute: StudentScheduleRoute,
  StudentSubscriptionRoute: StudentSubscriptionRoute,
  StudentWishlistRoute: StudentWishlistRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentCourseIdRoute: StudentCourseIdRoute,
  StudentQuizResultIdRoute: StudentQuizResultIdRoute,
  StudentQuizzesIdRoute: StudentQuizzesIdRoute,
  StudentQuizzesIndexRoute: StudentQuizzesIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRouteWithChildren,
  CoursesIdRoute: CoursesIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
