/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as InstructorRouteImport } from './routes/instructor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as StudentRouteImport } from './routes/student'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCoursesRouteImport } from './routes/admin.courses'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as CoursesIdRouteImport } from './routes/courses.$id'
import { Route as InstructorIndexRouteImport } from './routes/instructor.index'
import { Route as InstructorAnalyticsRouteImport } from './routes/instructor.analytics'
import { Route as InstructorCoursesRouteImport } from './routes/instructor.courses'
import { Route as InstructorDashboardRouteImport } from './routes/instructor.dashboard'
import { Route as InstructorEarningsRouteImport } from './routes/instructor.earnings'
import { Route as InstructorLiveRouteImport } from './routes/instructor.live'
import { Route as InstructorQuizzesRouteImport } from './routes/instructor.quizzes'
import { Route as InstructorReviewsRouteImport } from './routes/instructor.reviews'
import { Route as InstructorSettingsRouteImport } from './routes/instructor.settings'
import { Route as InstructorStudentsRouteImport } from './routes/instructor.students'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as StudentCertificatesRouteImport } from './routes/student.certificates'
import { Route as StudentCoursesRouteImport } from './routes/student.courses'
import { Route as StudentDashboardRouteImport } from './routes/student.dashboard'
import { Route as StudentLearnRouteImport } from './routes/student.learn'
import { Route as StudentScheduleRouteImport } from './routes/student.schedule'
import { Route as StudentSubscriptionRouteImport } from './routes/student.subscription'
import { Route as StudentWishlistRouteImport } from './routes/student.wishlist'
import { Route as StudentCourseIdRouteImport } from './routes/student.course.$id'
import { Route as StudentCoursesIdRouteImport } from './routes/student.courses.$id'
import { Route as StudentQuizResultIdRouteImport } from './routes/student.quiz-result.$id'
import { Route as StudentQuizzesIndexRouteImport } from './routes/student.quizzes.index'
import { Route as StudentQuizzesIdRouteImport } from './routes/student.quizzes.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorRoute = InstructorRouteImport.update({
  id: '/instructor',
  path: '/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCoursesRoute = AdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIdRoute = CoursesIdRouteImport.update({
  id: '/courses/$id',
  path: '/courses/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InstructorIndexRoute = InstructorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorAnalyticsRoute = InstructorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorCoursesRoute = InstructorCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorDashboardRoute = InstructorDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorEarningsRoute = InstructorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorLiveRoute = InstructorLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorQuizzesRoute = InstructorQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorReviewsRoute = InstructorReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorSettingsRoute = InstructorSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => InstructorRoute,
} as any)
const InstructorStudentsRoute = InstructorStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => InstructorRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCertificatesRoute = StudentCertificatesRouteImport.update({
  id: '/certificates',
  path: '/certificates',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesRoute = StudentCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDashboardRoute = StudentDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLearnRoute = StudentLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => StudentRoute,
} as any)
const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => StudentRoute,
} as any)
const StudentSubscriptionRoute = StudentSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => StudentRoute,
} as any)
const StudentWishlistRoute = StudentWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCourseIdRoute = StudentCourseIdRouteImport.update({
  id: '/course/$id',
  path: '/course/$id',
  getParentRoute: () => StudentRoute,
} as any)
const StudentCoursesIdRoute = StudentCoursesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentCoursesRoute,
} as any)
const StudentQuizResultIdRoute = StudentQuizResultIdRouteImport.update({
  id: '/quiz-result/$id',
  path: '/quiz-result/$id',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuizzesIndexRoute = StudentQuizzesIndexRouteImport.update({
  id: '/quizzes/',
  path: '/quizzes/',
  getParentRoute: () => StudentRoute,
} as any)
const StudentQuizzesIdRoute = StudentQuizzesIdRouteImport.update({
  id: '/quizzes/$id',
  path: '/quizzes/$id',
  getParentRoute: () => StudentRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$id': typeof CoursesIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/courses': typeof InstructorCoursesRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/earnings': typeof InstructorEarningsRoute
  '/instructor/live': typeof InstructorLiveRoute
  '/instructor/quizzes': typeof InstructorQuizzesRoute
  '/instructor/reviews': typeof InstructorReviewsRoute
  '/instructor/settings': typeof InstructorSettingsRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/learn': typeof StudentLearnRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/student/wishlist': typeof StudentWishlistRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/course/$id': typeof StudentCourseIdRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/quiz-result/$id': typeof StudentQuizResultIdRoute
  '/student/quizzes/$id': typeof StudentQuizzesIdRoute
  '/student/quizzes/': typeof StudentQuizzesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$id': typeof CoursesIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/courses': typeof InstructorCoursesRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/earnings': typeof InstructorEarningsRoute
  '/instructor/live': typeof InstructorLiveRoute
  '/instructor/quizzes': typeof InstructorQuizzesRoute
  '/instructor/reviews': typeof InstructorReviewsRoute
  '/instructor/settings': typeof InstructorSettingsRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/learn': typeof StudentLearnRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/student/wishlist': typeof StudentWishlistRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/instructor': typeof InstructorIndexRoute
  '/student': typeof StudentIndexRoute
  '/student/course/$id': typeof StudentCourseIdRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/quiz-result/$id': typeof StudentQuizResultIdRoute
  '/student/quizzes/$id': typeof StudentQuizzesIdRoute
  '/student/quizzes': typeof StudentQuizzesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/instructor': typeof InstructorRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/student': typeof StudentRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/courses': typeof AdminCoursesRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/courses/$id': typeof CoursesIdRoute
  '/instructor/analytics': typeof InstructorAnalyticsRoute
  '/instructor/courses': typeof InstructorCoursesRoute
  '/instructor/dashboard': typeof InstructorDashboardRoute
  '/instructor/earnings': typeof InstructorEarningsRoute
  '/instructor/live': typeof InstructorLiveRoute
  '/instructor/quizzes': typeof InstructorQuizzesRoute
  '/instructor/reviews': typeof InstructorReviewsRoute
  '/instructor/settings': typeof InstructorSettingsRoute
  '/instructor/students': typeof InstructorStudentsRoute
  '/student/certificates': typeof StudentCertificatesRoute
  '/student/courses': typeof StudentCoursesRouteWithChildren
  '/student/dashboard': typeof StudentDashboardRoute
  '/student/learn': typeof StudentLearnRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/subscription': typeof StudentSubscriptionRoute
  '/student/wishlist': typeof StudentWishlistRoute
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/instructor/': typeof InstructorIndexRoute
  '/student/': typeof StudentIndexRoute
  '/student/course/$id': typeof StudentCourseIdRoute
  '/student/courses/$id': typeof StudentCoursesIdRoute
  '/student/quiz-result/$id': typeof StudentQuizResultIdRoute
  '/student/quizzes/$id': typeof StudentQuizzesIdRoute
  '/student/quizzes/': typeof StudentQuizzesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/instructor'
    | '/login'
    | '/signup'
    | '/student'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/courses/$id'
    | '/instructor/analytics'
    | '/instructor/courses'
    | '/instructor/dashboard'
    | '/instructor/earnings'
    | '/instructor/live'
    | '/instructor/quizzes'
    | '/instructor/reviews'
    | '/instructor/settings'
    | '/instructor/students'
    | '/student/certificates'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/learn'
    | '/student/schedule'
    | '/student/subscription'
    | '/student/wishlist'
    | '/admin/'
    | '/courses/'
    | '/instructor/'
    | '/student/'
    | '/student/course/$id'
    | '/student/courses/$id'
    | '/student/quiz-result/$id'
    | '/student/quizzes/$id'
    | '/student/quizzes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/courses/$id'
    | '/instructor/analytics'
    | '/instructor/courses'
    | '/instructor/dashboard'
    | '/instructor/earnings'
    | '/instructor/live'
    | '/instructor/quizzes'
    | '/instructor/reviews'
    | '/instructor/settings'
    | '/instructor/students'
    | '/student/certificates'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/learn'
    | '/student/schedule'
    | '/student/subscription'
    | '/student/wishlist'
    | '/admin'
    | '/courses'
    | '/instructor'
    | '/student'
    | '/student/course/$id'
    | '/student/courses/$id'
    | '/student/quiz-result/$id'
    | '/student/quizzes/$id'
    | '/student/quizzes'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/instructor'
    | '/login'
    | '/signup'
    | '/student'
    | '/admin/analytics'
    | '/admin/courses'
    | '/admin/moderation'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/courses/$id'
    | '/instructor/analytics'
    | '/instructor/courses'
    | '/instructor/dashboard'
    | '/instructor/earnings'
    | '/instructor/live'
    | '/instructor/quizzes'
    | '/instructor/reviews'
    | '/instructor/settings'
    | '/instructor/students'
    | '/student/certificates'
    | '/student/courses'
    | '/student/dashboard'
    | '/student/learn'
    | '/student/schedule'
    | '/student/subscription'
    | '/student/wishlist'
    | '/admin/'
    | '/courses/'
    | '/instructor/'
    | '/student/'
    | '/student/course/$id'
    | '/student/courses/$id'
    | '/student/quiz-result/$id'
    | '/student/quizzes/$id'
    | '/student/quizzes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  InstructorRoute: typeof InstructorRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  StudentRoute: typeof StudentRouteWithChildren
  CoursesIdRoute: typeof CoursesIdRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor': {
      id: '/instructor'
      path: '/instructor'
      fullPath: '/instructor'
      preLoaderRoute: typeof InstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/courses': {
      id: '/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AdminCoursesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$id': {
      id: '/courses/$id'
      path: '/courses/$id'
      fullPath: '/courses/$id'
      preLoaderRoute: typeof CoursesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instructor/': {
      id: '/instructor/'
      path: '/'
      fullPath: '/instructor/'
      preLoaderRoute: typeof InstructorIndexRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/analytics': {
      id: '/instructor/analytics'
      path: '/analytics'
      fullPath: '/instructor/analytics'
      preLoaderRoute: typeof InstructorAnalyticsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/courses': {
      id: '/instructor/courses'
      path: '/courses'
      fullPath: '/instructor/courses'
      preLoaderRoute: typeof InstructorCoursesRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/dashboard': {
      id: '/instructor/dashboard'
      path: '/dashboard'
      fullPath: '/instructor/dashboard'
      preLoaderRoute: typeof InstructorDashboardRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/earnings': {
      id: '/instructor/earnings'
      path: '/earnings'
      fullPath: '/instructor/earnings'
      preLoaderRoute: typeof InstructorEarningsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/live': {
      id: '/instructor/live'
      path: '/live'
      fullPath: '/instructor/live'
      preLoaderRoute: typeof InstructorLiveRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/quizzes': {
      id: '/instructor/quizzes'
      path: '/quizzes'
      fullPath: '/instructor/quizzes'
      preLoaderRoute: typeof InstructorQuizzesRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/reviews': {
      id: '/instructor/reviews'
      path: '/reviews'
      fullPath: '/instructor/reviews'
      preLoaderRoute: typeof InstructorReviewsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/settings': {
      id: '/instructor/settings'
      path: '/settings'
      fullPath: '/instructor/settings'
      preLoaderRoute: typeof InstructorSettingsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/instructor/students': {
      id: '/instructor/students'
      path: '/students'
      fullPath: '/instructor/students'
      preLoaderRoute: typeof InstructorStudentsRouteImport
      parentRoute: typeof InstructorRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/certificates': {
      id: '/student/certificates'
      path: '/certificates'
      fullPath: '/student/certificates'
      preLoaderRoute: typeof StudentCertificatesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses': {
      id: '/student/courses'
      path: '/courses'
      fullPath: '/student/courses'
      preLoaderRoute: typeof StudentCoursesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/dashboard': {
      id: '/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof StudentDashboardRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/learn': {
      id: '/student/learn'
      path: '/learn'
      fullPath: '/student/learn'
      preLoaderRoute: typeof StudentLearnRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/schedule': {
      id: '/student/schedule'
      path: '/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/subscription': {
      id: '/student/subscription'
      path: '/subscription'
      fullPath: '/student/subscription'
      preLoaderRoute: typeof StudentSubscriptionRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/wishlist': {
      id: '/student/wishlist'
      path: '/wishlist'
      fullPath: '/student/wishlist'
      preLoaderRoute: typeof StudentWishlistRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/course/$id': {
      id: '/student/course/$id'
      path: '/course/$id'
      fullPath: '/student/course/$id'
      preLoaderRoute: typeof StudentCourseIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/courses/$id': {
      id: '/student/courses/$id'
      path: '/$id'
      fullPath: '/student/courses/$id'
      preLoaderRoute: typeof StudentCoursesIdRouteImport
      parentRoute: typeof StudentCoursesRoute
    }
    '/student/quiz-result/$id': {
      id: '/student/quiz-result/$id'
      path: '/quiz-result/$id'
      fullPath: '/student/quiz-result/$id'
      preLoaderRoute: typeof StudentQuizResultIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quizzes/': {
      id: '/student/quizzes/'
      path: '/quizzes'
      fullPath: '/student/quizzes/'
      preLoaderRoute: typeof StudentQuizzesIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/quizzes/$id': {
      id: '/student/quizzes/$id'
      path: '/quizzes/$id'
      fullPath: '/student/quizzes/$id'
      preLoaderRoute: typeof StudentQuizzesIdRouteImport
      parentRoute: typeof StudentRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCoursesRoute: typeof AdminCoursesRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCoursesRoute: AdminCoursesRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface InstructorRouteChildren {
  InstructorAnalyticsRoute: typeof InstructorAnalyticsRoute
  InstructorCoursesRoute: typeof InstructorCoursesRoute
  InstructorDashboardRoute: typeof InstructorDashboardRoute
  InstructorEarningsRoute: typeof InstructorEarningsRoute
  InstructorLiveRoute: typeof InstructorLiveRoute
  InstructorQuizzesRoute: typeof InstructorQuizzesRoute
  InstructorReviewsRoute: typeof InstructorReviewsRoute
  InstructorSettingsRoute: typeof InstructorSettingsRoute
  InstructorStudentsRoute: typeof InstructorStudentsRoute
  InstructorIndexRoute: typeof InstructorIndexRoute
}

const InstructorRouteChildren: InstructorRouteChildren = {
  InstructorAnalyticsRoute: InstructorAnalyticsRoute,
  InstructorCoursesRoute: InstructorCoursesRoute,
  InstructorDashboardRoute: InstructorDashboardRoute,
  InstructorEarningsRoute: InstructorEarningsRoute,
  InstructorLiveRoute: InstructorLiveRoute,
  InstructorQuizzesRoute: InstructorQuizzesRoute,
  InstructorReviewsRoute: InstructorReviewsRoute,
  InstructorSettingsRoute: InstructorSettingsRoute,
  InstructorStudentsRoute: InstructorStudentsRoute,
  InstructorIndexRoute: InstructorIndexRoute,
}

const InstructorRouteWithChildren = InstructorRoute._addFileChildren(
  InstructorRouteChildren,
)

interface StudentCoursesRouteChildren {
  StudentCoursesIdRoute: typeof StudentCoursesIdRoute
}

const StudentCoursesRouteChildren: StudentCoursesRouteChildren = {
  StudentCoursesIdRoute: StudentCoursesIdRoute,
}

const StudentCoursesRouteWithChildren = StudentCoursesRoute._addFileChildren(
  StudentCoursesRouteChildren,
)

interface StudentRouteChildren {
  StudentCertificatesRoute: typeof StudentCertificatesRoute
  StudentCoursesRoute: typeof StudentCoursesRouteWithChildren
  StudentDashboardRoute: typeof StudentDashboardRoute
  StudentLearnRoute: typeof StudentLearnRoute
  StudentScheduleRoute: typeof StudentScheduleRoute
  StudentSubscriptionRoute: typeof StudentSubscriptionRoute
  StudentWishlistRoute: typeof StudentWishlistRoute
  StudentIndexRoute: typeof StudentIndexRoute
  StudentCourseIdRoute: typeof StudentCourseIdRoute
  StudentQuizResultIdRoute: typeof StudentQuizResultIdRoute
  StudentQuizzesIdRoute: typeof StudentQuizzesIdRoute
  StudentQuizzesIndexRoute: typeof StudentQuizzesIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentCertificatesRoute: StudentCertificatesRoute,
  StudentCoursesRoute: StudentCoursesRouteWithChildren,
  StudentDashboardRoute: StudentDashboardRoute,
  StudentLearnRoute: StudentLearnRoute,
  StudentScheduleRoute: StudentScheduleRoute,
  StudentSubscriptionRoute: StudentSubscriptionRoute,
  StudentWishlistRoute: StudentWishlistRoute,
  StudentIndexRoute: StudentIndexRoute,
  StudentCourseIdRoute: StudentCourseIdRoute,
  StudentQuizResultIdRoute: StudentQuizResultIdRoute,
  StudentQuizzesIdRoute: StudentQuizzesIdRoute,
  StudentQuizzesIndexRoute: StudentQuizzesIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  InstructorRoute: InstructorRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  StudentRoute: StudentRouteWithChildren,
  CoursesIdRoute: CoursesIdRoute,
  CoursesIndexRoute: CoursesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
